#!/usr/bin/perl -w -n

next if /^use lib/;

s|^#!/usr.*|#!/usr/bin/perl -w|;
s|^my \$VERSION.*|my \$VERSION='$ENV{VERSION}';|;
$skip=1 if /^# local start/;
$skip=0 if /^# local end/;
next    if /^# local end/;


next if $skip;

print;
